services:
  pinformation-bot:
    build:
      context: .
      dockerfile: Dockerfile
    
    container_name: pinformation_bot
    volumes:
      - ./pinformation_bot/config:/app/pinformation_bot/config
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - LOG_LEVEL=DEBUG
    restart: unless-stopped
